# Generated by Django 4.0.5 on 2022-06-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='defaultAvatar.png', null=True, upload_to='pofile_images'),
        ),
    ]
