# Generated by Django 4.0.5 on 2022-06-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='defaultAvatar.png', null=True, upload_to='profile_images'),
        ),
    ]
