# Generated by Django 4.0.5 on 2022-06-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookLocation',
            field=models.CharField(choices=[('HOME', 'Home'), ('OFFICE', 'Office'), ('INTO THE MATRIX', 'Into the Matrix')], default='Home', max_length=30),
        ),
        migrations.AddField(
            model_name='books',
            name='coverImage',
            field=models.ImageField(blank=True, default='defaultCover.png', null=True, upload_to='books_images'),
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default="User hasn't placed a bio yet.", max_length=300),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookType',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('PAPERBACK', 'Paperback'), ('DIGITAL', 'Digital')], default='Physical', max_length=12),
        ),
    ]
