# Generated by Django 4.0.5 on 2022-07-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_user_books_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='owner',
            new_name='user',
        ),
    ]
