# Generated by Django 4.0.5 on 2022-07-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_books_likes_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='books',
            new_name='book',
        ),
    ]
