# Generated by Django 4.0.5 on 2022-07-07 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_rename_books_comment_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='likes',
            field=models.ManyToManyField(related_name='books_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
