# Generated by Django 4.0.5 on 2022-07-07 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0009_alter_books_authoremail_alter_books_authorname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='isAvailable',
        ),
        migrations.CreateModel(
            name='BooksBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAvailable', models.BooleanField(default=True)),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('isReturned', models.BooleanField(default=False)),
                ('return_date', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book', to='books.books')),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_borrower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-borrow_date'],
            },
        ),
    ]
