# Generated by Django 4.0.5 on 2022-07-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_books_isavailable_booksborrow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksBorrow',
        ),
    ]
