# Generated by Django 4.0.5 on 2022-07-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_delete_booksborrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='likes',
        ),
    ]
